spring.application.name=sboot-atom-pais


## PostgreSQL ###
spring.datasource.url=jdbc:postgresql://localhostuat:5432/basic
spring.datasource.username=postgresuat
spring.datasource.password=postgresuat