spring.application.name=sboot-atom-pais


## PostgreSQL ###
spring.datasource.url=jdbc:postgresql://localhostprd:5432/basic
spring.datasource.username=postgresprd
spring.datasource.password=postgresprd