spring:
  application:
    name: sboot-atom-pais
#  jpa:
#    hibernate:
#      ddl-auto: create # drop n create table again, good for testing, comment this in production

  datasource:
    url: jdbc:postgresql://localhost:5432/scaqd
    username: postgres
    password: postgres



server:
  port: 8081

