spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/scaqd
    username: postgres
    password: postgres
  jpa:
    show-sql: true
 ################################### KAFKA ####################################
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group_id
################################ MAPEAMENTO DE TOPICOS CRIADOS ####################
topic1:
  name:
    consumer: meu-topico-1
    producer: meu-topico-produce-1
topic2:
  name:
    consumer: meu-topico-2

server:
  port: 8081